### ISSUE TITLE
domain_of_validity() results in error

### ISSUE THREAD

**Issue by dopplershift** [rhattersley/pyepsg#15]
The call to `domain_of_validity()` is now resulting in an error:
```python
import pyepsg
proj = pyepsg.get(3857)
proj.domain_of_validity()
```
yields
```pytb
Traceback (most recent call last):

  File "/Users/rmay/miniconda3/envs/py38/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3319, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-7-89bf4603e739>", line 3, in <module>
    proj.domain_of_validity()

  File "/Users/rmay/miniconda3/envs/py38/lib/python3.8/site-packages/pyepsg.py", line 205, in domain_of_validity
    gml = ET.fromstring(xml)

  File "/Users/rmay/miniconda3/envs/py38/lib/python3.8/xml/etree/ElementTree.py", line 1320, in XML
    parser.feed(text)

  File "<string>", line unknown
ParseError: mismatched tag: line 33, column 4
```

The error results in this case from trying to access the url: http://epsg.io/urn:ogc:def:area:EPSG::3544.gml?download
which you can see results in a 500 error page. My best guess is maybe previously the domain was returned as e.g. 3544 and not "urn:ogc:def:area:EPSG::3544"? Just a guess. Regardless, the function is unusable and causes CartoPy to error out whenever trying to use the EPSG functionality.

**Comment by weatherfrog** [comment]
The service https://epsg.io seems to be broken. For example, the link displayed here:
https://epsg.io/?q=2056
results in 500:
https://epsg.io/2056

**Comment by mjarrett** [comment]
This is now fixed, see: https://github.com/maptiler/epsg.io/issues/156
